print ("This is a serious virus if you use the company or any one is not responsible  ")
input("press enter to continue")
print ("Waring-This is the last warinig by using this you will make your system unbootable")
input("press enter to continue ")
print ("deleting major system files")
print ("C:\Windows\security-The command you are executing may be harmful to your computer components")
input("press (Y/N)")
print ("deleting boot files to make system unbootable")
input("C:\Windows\Boot")
print ("deleting files in system32")
print ("C:\Windows\System32-virus.py files make changes to Hard Drive")
input("press (Y/N)")
print ("system security - unable to fix the problem")
input('press enter to shutdown and make system unbootable')
print ("you have gone pranked")
input('press enter to exit from this python file')
exit()


